; For CapHacker / HackerCapNFC (SPI, ST25R3916)

; --------------------------------
; UnitTest
; --------------------------------
; CapHacker (SPI) - Cardputer only
[env:test_CapHacker_CardputerADV]
extends=Cardputer, option_release, arduino_latest
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP
lib_deps = ${Cardputer.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_st25r3916

; --------------------------------
; Examples
; --------------------------------
; CapHacker
; ---- NFC-A
[env:CapHacker_NFCA_Detect_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/Detect>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCA_Dump_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/Dump>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCA_ReadWrite_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/ReadWrite>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCA_ValueBlock_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/ValueBlock>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCA_NDEF_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/NDEF>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCA_Emulation_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/Emulation>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

; ---- NFC-B
[env:CapHacker_NFCB_Detect_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCB/Detect>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCB_JapanIDCard_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCB/JapanIDCard>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

; ---- NFC-F
[env:CapHacker_NFCF_Detect_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Detect>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCF_Dump_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Dump>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCF_NDEF_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/NDEF>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCF_Subtract_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Subtract>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCF_ReadWriteMAC_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/ReadWriteMAC>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCF_JapanTransportationICCard_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/JapanTransportationICCard>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCF_Emulation_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Emulation>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

; ---- NFC-V
[env:CapHacker_NFCV_Detect_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCV/Detect>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCV_Dump_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCV/Dump>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

[env:CapHacker_NFCV_NDEF_CardputerADV_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCV/NDEF>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
  -D USING_HACKER_CAP

;------------------------------------
[env:UnitNFC_NFCA_Dump_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/Dump>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_ReadWrite_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/ReadWrite>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_ValueBlock_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/ValueBlock>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_NDEF_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/NDEF>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_Emulation_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/Emulation>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC


[env:UnitNFC_NFCF_Dump_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Dump>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_NDEF_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/NDEF>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_Subtract_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Subtract>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_ReadWriteMAC_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/ReadWriteMAC>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_JapanTransportationICCard_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/JapanTransportationICCard>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_Emulation_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Emulation>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCV_Dump_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCV/Dump>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCV_NDEF_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCV/NDEF>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCB_JapanIDCard_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCB/JapanIDCard>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

;------------
[env:UnitNFC_NFCA_Dump_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/Dump>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_ReadWrite_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/ReadWrite>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_ValueBlock_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/ValueBlock>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_NDEF_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/NDEF>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCA_Emulation_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCA/Emulation>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC


[env:UnitNFC_NFCF_Dump_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Dump>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_NDEF_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/NDEF>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_Subtract_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Subtract>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_ReadWriteMAC_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/ReadWriteMAC>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_JapanTransportationICCard_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/JapanTransportationICCard>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCF_Emulation_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCF/Emulation>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCV_Dump_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCV/Dump>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCV_NDEF_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCV/NDEF>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC

[env:UnitNFC_NFCB_JapanIDCard_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/NFCB/JapanIDCard>
build_flags = ${option_release.build_flags}
  -D USING_UNIT_NFC
