name=M5Unit-NFC
version=0.0.1
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT NFC using M5UnitUnified
paragraph=
category=Device Control
url=https://github.com/m5stack/M5Unit-NFC
architectures=esp32
includes=M5UnitUnifiedNFC.h
depends=M5UnitUnified,M5Utility,M5HAL
