;-----------------------------------------------------------------------
; M5Unit-NFC
; For UnitTest and examples (Using M5UnitUnified)
;-----------------------------------------------------------------------
[platformio]

[env]
build_flags =  -Wall -Wextra -Wreturn-local-addr -Werror=format -Werror=return-local-addr
lib_ldf_mode = deep
test_framework = googletest
test_build_src = true
lib_deps=m5stack/M5Unified
  m5stack/M5UnitUnified#develop
;  m5stack/M5Utility#develop

; --------------------------------
[m5base]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000
test_speed = 115200
test_ignore= native/*

[CardputerADV]
extends = m5base
;platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
lib_deps = ${env.lib_deps}

; --------------------------------
;Choose framework
[arduino_latest]
platform = espressif32 @ 6.8.1
framework = arduino

;[esp-idf]
;platform = espressif32 @ 6.8.1
;framework = espidf

; --------------------------------
;Choose build options
[option_release]
build_type=release
build_flags = ${env.build_flags}   
  -DCORE_DEBUG_LEVEL=3
  -DLOG_LOCAL_LEVEL=3
  -DAPP_LOG_LEVEL=3
  -DM5_LOG_LEVEL=3

[option_log]
build_type=release
build_flags = ${env.build_flags} 
  -DCORE_DEBUG_LEVEL=5
  -DLOG_LOCAL_LEVEL=5
  -DAPP_LOG_LEVEL=5

[option_debug]
build_type=debug
build_flags = ${env.build_flags} 
  -DCORE_DEBUG_LEVEL=5
  -DLOG_LOCAL_LEVEL=5
  -DAPP_LOG_LEVEL=5
  -DDEBUG

[option_map]
build_type=release
build_flags = ${env.build_flags} 
  -DCORE_DEBUG_LEVEL=3
  -DLOG_LOCAL_LEVEL=3
  -DAPP_LOG_LEVEL=3
  -DM5_LOG_LEVEL=0
  -Wl,-Map,output.map

; Require at leaset C++14 after 1.13.0 
[test_fw]
lib_deps = google/googletest@1.12.1

; --------------------------------
; UnitTest
; --------------------------------
[env:test_ST25R3916_CardputerADV]
extends=CardputerADV, option_release, arduino_latest
lib_deps = ${CardputerADV.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_st25r3916

; --------------------------------
;Examples 
; --------------------------------
;CapHacker
[env:CapHacker_DetectDevices_CardputerADV_Arduino_latest]
extends=CardputerADV, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/DetectDevices>
build_flags = ${option_release.build_flags}
  -DUSING_CAP_ST25R3916

[env:CapHacker_Dump_CardputerADV_Arduino_latest]
extends=CardputerADV, option_debug, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/Dump>
build_flags = ${option_release.build_flags}
  -DUSING_CAP_ST25R3916

